[package]
name = "hellscaper"
version = "0.1.0"
edition = "2024"

[dependencies]
poise = "0.6.1"
rand = "0.8"
regex = "1.12"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "1.21.2", features = ["macros", "rt-multi-thread"] }
toml = "0.9"
